# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test Java Versioning Proj

on:
  push:
    branches: [ "main", "test-branch" ]
  pull_request:
    branches: [ "main", "test-branch" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: mrtngrangerhg/springboot-image-test # ratchet:ubuntu:latest
        tags: v1, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: ratchet
      uses: docker://ghcr.io/sethvargo/ratchet:0.2.3
      with:
        args: "./ratchet check .github/workflows/maven.yml"
  # ratchet:
  #   runs-on: ubuntu-latest
  #   name: ratchet
  #   steps:
  #   # - name: ratchet
  #   #   uses: ratchet:actions/checkout@v3

  #   - uses: docker://ghcr.io/sethvargo/ratchet:0.2.3
  #     with:
  #       args: "pin .github/workflows/maven.yml"